# https://docs.codecov.com/docs/common-recipe-list
comment:
  require_changes: true

# https://docs.codecov.com/docs/ignoring-paths
ignore:
  - "deep_causality/examples"  # ignore folders and all its contents