# The Manifest Format
# https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["macros"]

[workspace.package]
version = "0.4.0"
edition = "2021"
rust-version = "1.65"
repository = "https://github.com/deepcausality/deep_causality.rs"
authors = ["Marvin Hansen <marvin.hansen@gmail.com>", ]

[package]
name = "deep_causality_rs"
version = "0.0.1"
edition = "2021"
rust-version = "1.65"
readme = "README.md"
license = "MIT"

description = "Computational causality library. Provides causality graph, collections, context and causal reasoning."
#documentation = ""
#homepage = ""
repository = "https://github.com/deepcausality/deep_causality.rs"
keywords = ["cauality","causal-data-structure", "causal-graph","causal-reasoning","graph"]
categories = ["data-structures","science","aerospace","finance","mathematics"]
authors = ["Marvin Hansen <marvin.hansen@gmail.com>", ]

[dependencies]
# using a patched version of petgraph until PR #547 went through
petgraph = { git = "https://github.com/marvin-hansen/petgraph.git", rev = "a685be8" }

[dependencies.macros]
path = "macros"
version = "^0.4.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
rand = { version = "0.8.5", features = ["small_rng"] }

#[[bench]]
#name = "bench_main"
#harness = false

[profile.release]
strip = true  # Automatically strip debug symbols from the binary
lto = true    # Enable Link Time Optimization (LTO)
codegen-units = 1 # Reduce Parallel Code Generation Units to Increase Optimization
panic = "abort"  # disabled