[package]
name = "example-csm"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
#deep_causality = "0.2.8"
deep_causality = { git = "https://github.com/deepcausality-rs/deep_causality.git", tag = "0.2.9"}