[package]
name = "example-ctx"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"
publish = false


[dependencies]
# For testing with latest commit in main
#deep_causality = { git = "https://github.com/deepcausality-rs/deep_causality", branch = "main" }
deep_causality = "0.6.2"

# chrono default-features = false mitigates "RUSTSEC-2020-0071".
# See https://rustsec.org/advisories/RUSTSEC-2020-0071.html
chrono = { version = "0.4", default-features = false , features = ["serde", "clock"] }
parquet = "48.0.0"
petgraph = "0.6"
rust_decimal = "1.32"
serde = { version = "1.0", features = ["derive"] }
