[package]
name = "dcl_data_structures"
version = "0.6.0"
edition = "2021"
rust-version = "1.80"
repository = "https://github.com/deepcausality/deep_causality.rs"
authors = ["Marvin Hansen <marvin.hansen@gmail.com>", ]
license = "MIT"
description = "Data structures for for deep_causality crate."
documentation = "https://docs.rs/deep_causality"
categories = ["data-structures", "science"]
keywords = ["data-structures", "sliding-window", "grid-array"]

[features]
default = []
unsafe = [] # Enable unsafe implementations

[dev-dependencies]
crossbeam-utils = "0.8"
criterion = { version = "0.5", features = ["html_reports"] }
rand = { version = "0.8", features = ["small_rng"] }

[[bench]]
name = "bench_dcl_data_structures"
harness = false
