[package]
name = "deep_causality_macros"
version = "0.4.0"
edition = "2021"
rust-version = "1.65"
repository = "https://github.com/deepcausality/deep_causality.rs"
authors = ["Marvin Hansen <marvin.hansen@gmail.com>", ]
license = "MIT"

description = "Procedural macros for use with deep_causality."
documentation = "https://docs.rs/deep_causality"


[lib]
proc-macro = true

[features]


[dependencies]


[package.metadata.docs.rs]
all-features = true