name: Security Audit

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  security_audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore: RUSTSEC-2020-0071