name: Phylum_analyze
on: pull_request

jobs:
  analyze_deps:
    name: Analyze dependencies with Phylum
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
#
# Disabled due to issue https://github.com/phylum-dev/phylum-analyze-pr-action/issues/29
#
#      - name: Analyze dependencies
#        uses: phylum-dev/phylum-analyze-pr-action@v2
#        with:
#          phylum_token: ${{ secrets.PHYLUM_TOKEN }}
#          # Mix and match for your specific use case.
#          cmd: |
#            phylum-ci \
#              -vv \
#              --lockfile ./Cargo.toml \
#              --all-deps
