name: Rustfmt

on: pull_request

jobs:
  format:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "date=$(date -d '1 month ago' +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-${{ env.date }}
          components: rustfmt
      - uses: LoliGothick/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
#          toolchain: nightly-${{ env.date }}
#          flags: --all
#          options: --manifest-path=Cargo.toml
#          args: --config-path=path/to/rustfmt.toml
#          working-directory: my_crate
